[theme]
[theme]
primaryColor="#6366F1"
backgroundColor="#020617"
textColor="#E5E7EB"
secondaryBackgroundColor = "#F0F2F6"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
